// Reference lists for dropdowns. Update here to add or rename entries —
// kept alphabetical for easier scanning. Anything not in the list is
// captured via the "Other" option on each select.

export const MALAYSIAN_MEDIA_COMPANIES = [
  'Astro',
  'Astro Awani',
  'Bernama',
  'Berita Harian',
  'BFM 89.9',
  'China Press',
  'Daily Express (Sabah)',
  'Focus Malaysia',
  'Forbes Malaysia',
  'Free Malaysia Today',
  'Harian Metro',
  'Kosmo!',
  'Malay Mail',
  'Malaysiakini',
  'Malaysian Business',
  'MalaysiaNow',
  'Media Prima',
  'Nanyang Siang Pau',
  'New Straits Times',
  'RTM (TV1)',
  'RTM (TV2)',
  'See Hua Daily News',
  'Sin Chew Daily',
  'Sinar Harian',
  'The Borneo Post',
  'The Edge Financial Daily',
  'The Edge Malaysia',
  'The Edge Markets',
  'The Malaysian Insight',
  'The Malaysian Reserve',
  'The Star',
  'The Sun',
  'The Vibes',
  'Utusan Malaysia',
] as const;

export const ANALYST_INSTITUTIONS = [
  'Aberdeen Standard Investments',
  'Affin Hwang Investment Bank',
  'AmInvestment Bank',
  'Apex Securities',
  'BlackRock',
  'BNP Paribas Securities',
  'CIMB Investment Bank',
  'Citigroup Global Markets',
  'Credit Suisse',
  'DBS Bank',
  'Eastspring Investments',
  'Fidelity Investments',
  'Goldman Sachs',
  'Hong Leong Investment Bank',
  'HSBC Securities',
  'Inter-Pacific Securities',
  'Jefferies',
  'JP Morgan',
  'Kenanga Investment Bank',
  'KGI Securities',
  'Macquarie',
  'Manulife Investment Management',
  'Maybank Investment Bank',
  'MIDF Amanah Investment Bank',
  'Morgan Stanley',
  'Nomura',
  'PHEIM Asset Management',
  'Phillip Capital',
  'Public Investment Bank',
  'Public Mutual',
  'RHB Investment Bank',
  'Schroders',
  'T. Rowe Price',
  'TA Securities',
  'Templeton',
  'UBS',
  'UOB Kay Hian',
  'Vanguard',
] as const;
